// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	projectmodels "github.com/10Narratives/ready-to-do/server/internal/models/tasks/project"
	mock "github.com/stretchr/testify/mock"

	status "google.golang.org/grpc/status"
)

// ProjectStorage is an autogenerated mock type for the ProjectStorage type
type ProjectStorage struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, project
func (_m *ProjectStorage) Create(ctx context.Context, project *projectmodels.Project) *status.Status {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *status.Status
	if rf, ok := ret.Get(0).(func(context.Context, *projectmodels.Project) *status.Status); ok {
		r0 = rf(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*status.Status)
		}
	}

	return r0
}

// NewProjectStorage creates a new instance of ProjectStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectStorage {
	mock := &ProjectStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
