// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: tracker/v1/project_service.proto

package trackerv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_tracker_v1_project_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_v1_project_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_tracker_v1_project_service_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int64                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_tracker_v1_project_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_v1_project_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_tracker_v1_project_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListProjectsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProjectsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_tracker_v1_project_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_v1_project_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_tracker_v1_project_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_tracker_v1_project_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_v1_project_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_tracker_v1_project_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Project       *Project               `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_tracker_v1_project_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_v1_project_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_tracker_v1_project_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProjectRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateProjectRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_tracker_v1_project_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_v1_project_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_tracker_v1_project_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProjectRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *UpdateProjectRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_tracker_v1_project_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_v1_project_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_tracker_v1_project_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_tracker_v1_project_service_proto protoreflect.FileDescriptor

const file_tracker_v1_project_service_proto_rawDesc = "" +
	"\n" +
	" tracker/v1/project_service.proto\x12\n" +
	"tracker.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xc2\x02\n" +
	"\aProject\x12:\n" +
	"\x04name\x18\x01 \x01(\tB&\xe0A\b\xfaB r\x1e\x18(2\x1a^projects/[a-z0-9-]{4,30}$R\x04name\x12/\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\f\xe0A\x02\xfaB\x06r\x04\x10\x02\x182R\vdisplayName\x12>\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAt:J\xeaAG\n" +
	"\x1etodoapp.googleapis.com/Project\x12\x12projects/{project}*\bprojects2\aproject\"Q\n" +
	"\x13ListProjectsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"o\n" +
	"\x14ListProjectsResponse\x12/\n" +
	"\bprojects\x18\x01 \x03(\v2\x13.tracker.v1.ProjectR\bprojects\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"'\n" +
	"\x11GetProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"|\n" +
	"\x14CreateProjectRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12-\n" +
	"\aproject\x18\x03 \x01(\v2\x13.tracker.v1.ProjectR\aproject\"\x82\x01\n" +
	"\x14UpdateProjectRequest\x12-\n" +
	"\aproject\x18\x01 \x01(\v2\x13.tracker.v1.ProjectR\aproject\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"*\n" +
	"\x14DeleteProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xc1\x04\n" +
	"\x0eProjectService\x12m\n" +
	"\fListProjects\x12\x1f.tracker.v1.ListProjectsRequest\x1a .tracker.v1.ListProjectsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1alpha1/Projects\x12e\n" +
	"\n" +
	"GetProject\x12\x1d.tracker.v1.GetProjectRequest\x1a\x13.tracker.v1.Project\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1alpha1/{name=Projects/*}\x12k\n" +
	"\rCreateProject\x12 .tracker.v1.CreateProjectRequest\x1a\x13.tracker.v1.Project\"#\x82\xd3\xe4\x93\x02\x1d:\aProject\"\x12/v1alpha1/Projects\x12|\n" +
	"\rUpdateProject\x12 .tracker.v1.UpdateProjectRequest\x1a\x13.tracker.v1.Project\"4\x82\xd3\xe4\x93\x02.:\aProject2#/v1alpha1/{Project.name=Projects/*}\x12n\n" +
	"\rDeleteProject\x12 .tracker.v1.DeleteProjectRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/v1alpha1/{name=Projects/*}BHZFgithub.com/10Narratives/ready-to-do/contracts/pkg/tracker/v1;trackerv1b\x06proto3"

var (
	file_tracker_v1_project_service_proto_rawDescOnce sync.Once
	file_tracker_v1_project_service_proto_rawDescData []byte
)

func file_tracker_v1_project_service_proto_rawDescGZIP() []byte {
	file_tracker_v1_project_service_proto_rawDescOnce.Do(func() {
		file_tracker_v1_project_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracker_v1_project_service_proto_rawDesc), len(file_tracker_v1_project_service_proto_rawDesc)))
	})
	return file_tracker_v1_project_service_proto_rawDescData
}

var file_tracker_v1_project_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tracker_v1_project_service_proto_goTypes = []any{
	(*Project)(nil),               // 0: tracker.v1.Project
	(*ListProjectsRequest)(nil),   // 1: tracker.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),  // 2: tracker.v1.ListProjectsResponse
	(*GetProjectRequest)(nil),     // 3: tracker.v1.GetProjectRequest
	(*CreateProjectRequest)(nil),  // 4: tracker.v1.CreateProjectRequest
	(*UpdateProjectRequest)(nil),  // 5: tracker.v1.UpdateProjectRequest
	(*DeleteProjectRequest)(nil),  // 6: tracker.v1.DeleteProjectRequest
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 8: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_tracker_v1_project_service_proto_depIdxs = []int32{
	7,  // 0: tracker.v1.Project.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: tracker.v1.Project.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: tracker.v1.ListProjectsResponse.projects:type_name -> tracker.v1.Project
	0,  // 3: tracker.v1.CreateProjectRequest.project:type_name -> tracker.v1.Project
	0,  // 4: tracker.v1.UpdateProjectRequest.project:type_name -> tracker.v1.Project
	8,  // 5: tracker.v1.UpdateProjectRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 6: tracker.v1.ProjectService.ListProjects:input_type -> tracker.v1.ListProjectsRequest
	3,  // 7: tracker.v1.ProjectService.GetProject:input_type -> tracker.v1.GetProjectRequest
	4,  // 8: tracker.v1.ProjectService.CreateProject:input_type -> tracker.v1.CreateProjectRequest
	5,  // 9: tracker.v1.ProjectService.UpdateProject:input_type -> tracker.v1.UpdateProjectRequest
	6,  // 10: tracker.v1.ProjectService.DeleteProject:input_type -> tracker.v1.DeleteProjectRequest
	2,  // 11: tracker.v1.ProjectService.ListProjects:output_type -> tracker.v1.ListProjectsResponse
	0,  // 12: tracker.v1.ProjectService.GetProject:output_type -> tracker.v1.Project
	0,  // 13: tracker.v1.ProjectService.CreateProject:output_type -> tracker.v1.Project
	0,  // 14: tracker.v1.ProjectService.UpdateProject:output_type -> tracker.v1.Project
	9,  // 15: tracker.v1.ProjectService.DeleteProject:output_type -> google.protobuf.Empty
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_tracker_v1_project_service_proto_init() }
func file_tracker_v1_project_service_proto_init() {
	if File_tracker_v1_project_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracker_v1_project_service_proto_rawDesc), len(file_tracker_v1_project_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracker_v1_project_service_proto_goTypes,
		DependencyIndexes: file_tracker_v1_project_service_proto_depIdxs,
		MessageInfos:      file_tracker_v1_project_service_proto_msgTypes,
	}.Build()
	File_tracker_v1_project_service_proto = out.File
	file_tracker_v1_project_service_proto_goTypes = nil
	file_tracker_v1_project_service_proto_depIdxs = nil
}
